server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: ${CONTEXT_PATH:}

spring:
  application.name: ${APPLICATION_NAME:example-app}

  banner:
    location: classpath:banner.txt

  flyway:
    enabled: ${FLYWAY_ENABLE:true}
    baseline-on-migrate: ${FLYWAY_BASELINE_ON_MIGRATE:true}
    validate-on-migrate: ${FLYWAY_VALIDATE_ON_MIGRATE:true}
    locations: classpath:db/migration

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/boilerplate}
    username: ${DB_USERNAME:user}
    password: ${DB_PASSWORD:password}
    driver-class-name: ${DB_DRIVER:org.postgresql.Driver}
    hikari:
      minimum-idle: ${HIKARI_MIN_POOL:10}
      maximum-pool-size: ${HIKARI_MAX_POOL:25}
      connection-timeout: ${HIKARI_CONNECTION_TIMEOUT:5000}
      idle-timeout: ${HIKARI_IDLE_TIMEOUT:60000}
      max-lifetime: ${HIKARI_MAX_LIFETIME:300000}

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: false
    show-sql: ${JPA_SHOW_SQL:true}
    hibernate:
      ddl-auto: none
    properties:
      hibernate.format_sql: ${HIBERNATE_FORMAT_SQL:true}

logging:
  level:
    root: ${ROOT_LOG_LEVEL:INFO}
    org.springframework: ${SPRING_LOG_LEVEL:INFO}
    org.hibernate: ${HIBERNATE_LOG_LEVEL:WARN}
    com.nantaaditya: ${APP_LOG_LEVEL:INFO}
  file.name: ${LOG_PATH:/}

management:
  server.port: ${ACTUATOR_PORT:1001}