server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: ${APP_NAME:single-module-reactive}
  webflux:
    base-path: ${CONTEXT_PATH:/app}
  r2dbc:
    url: ${R2DBC_URL:r2dbc:postgresql://localhost:5432/boilerplate}
    username: ${DB_USERNAME:user}
    password: ${DB_PASSWORD:password}
    pool:
      enabled: true
      initial-size: ${R2DBC_INITIAL_POOL:10}
      max-size: ${R2DBC_MAX_POOL:20}
      validation-query: SELECT 1
  flyway:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/boilerplate}
    user: ${DB_USERNAME:user}
    password: ${DB_PASSWORD:password}
    enabled: ${FLYWAY_ENABLED:false}
    validate-on-migrate: ${FLYWAY_VALIDATION_ENABLED:false}
    locations: classpath:db/migration

management:
  server:
    port: ${ACTUATOR_PORT:1000}
  endpoint:
    shutdown.access: ${ACTUATOR_SHUTDOWN:none}
    health.show-details: ${HEALTH_DETAIL:always}
  endpoints:
    web:
      exposure.include: ${ACTUATOR_EXPOSED:*}
  tracing:
    sampling:
      probability: ${TRACING_SAMPLING_PROBABILITY:1.0}
    baggage:
      remote-fields:
        - x-client-id
        - x-request-id
      correlation:
        fields:
          - x-client-id
          - x-request-id

logging:
  level:
    root: ${ROOT_LOG_LEVEL:INFO}
    com.nantaaditya: ${APP_LOG_LEVEL:INFO}
    org.zalando.logbook: ${ZALANDO_LOG_LEVEL:TRACE}
  file:
    path: ${LOG_FILE_PATH:logs/}
  pattern:
    console: '{"timestamp":"%d{yyyy-MM-dd HH:mm:ss:SSS}", "level":"%level", "app_version":"${apps.version}", "class": "%logger{36}", "message":"%enc{%replace{%message}{[\r\n]+}{}}{JSON}. %enc{%replace{%xThrowable}{[\r\n]+}{|}}{JSON}", "trace_id":"%X{traceId}", "span_id":"%X{spanId}", "request_id":"%X{x-request-id}"}\n'
    file: '{"timestamp":"%d{yyyy-MM-dd HH:mm:ss:SSS}", "level":"%level", "app_version":"${apps.version}", "class": "%logger{36}", "message":"%enc{%replace{%message}{[\r\n]+}{}}{JSON}. %enc{%replace{%xThrowable}{[\r\n]+}{|}}{JSON}", "trace_id":"%X{traceId}", "span_id":"%X{spanId}", "request_id":"%X{x-request-id}"}\n'

apps:
  version: ${APP_VERSION:1.0.0}
  log:
    enable-trace-log: ${ENABLE_TRACE_LOG:true}
    ignored-trace-log-path: ${IGNORED_TRACE_LOG_PATH:*/swagger-ui,*/swagger-ui/*,*/v3/api-docs,*/v3/api-docs/*}
    sensitive-field: ${SENSITIVE_FIELDS:x-client-id}
  scheduler.configurations:
    default-async:
      scheduler-type: BOUNDED_ELASTIC
      bounded-elastic:
        name: default-async
        daemon: true
        core-pool-size: 5
        queue-size: 10
        ttl-in-seconds: 60
    retry-listener:
      scheduler-type: BOUNDED_ELASTIC
      bounded-elastic:
        name: retry-listener
        daemon: true
        core-pool-size: 10
        queue-size: 20
        ttl-in-seconds: 60
